### ISSUE TITLE
UI Widgets Tracking Issue

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#54]
**Text**
- [ ] Label
- [ ] Static text area

**Button**
- [ ] Normal text button
- [ ] Toggle text button
- [ ] Normal image button
- [ ] Toggle image button

**Input**
- [ ] Text input box
- [ ] List select
- [ ] Vertical scroll bar
- [ ] Dropdown select with button on left
- [ ] Dropdown select with button on right

**Other**
- [ ] Mouse cursor (#49)
- [ ] Modal dialog
- [ ] Minimap

**Comment by phrohdoh** [comment]
So, I've been doing some thinking about this.
It is very unfortunate that Rust is so young an immature especially regarding UI toolkits.

I considered using Servo/WebRender but:

```
6:52:29 PM notriddle WebRender's API is unstable, though probably a better fit than trying to use servo/layout for that. 
6:52:38 PM Phrohdoh So I wouldn't be able to render the finalized HTML over the gl context/buffer? 
6:52:41 PM notriddle But that's not layout. 
6:53:46 PM notriddle Phrohdoh: The problem isn't with that. The problem is that you can't separate Servo's DOM from Spidermonkey, and you can't separate layout from Servo's DOM. 
6:54:13 PM notriddle And you don't want to pull in a JS runtime just for a GUI toolkit. 
```

Possible options:

https://github.com/PistonDevelopers/conrod

https://github.com/dcampbell24/iup-rust

https://github.com/kenz-gelsoft/wxRust

https://github.com/cyndis/qmlrs

PS come back to IRC!

**Comment by angered-ghandi** [comment]
I did some investigation into Conrod. It looks promising, but I don't think it's quite ready yet:
https://github.com/angered-ghandi/OpenAOE/issues/50

**Comment by phrohdoh** [comment]
There is also https://github.com/tomaka/immi which may be worth investigating as the basis for our UI.
