### ISSUE TITLE
Minimum playability tracking issue

### ISSUE THREAD

**Issue by angered-ghandi** [angered-ghandi/OpenAOE#58]
This issue tracks the **minimum** amount of work needed to be done in order for someone to play a conquest scenario to victory/defeat. The items in this issue should drive the development of this project for the foreseeable future.
- [ ] **Unit interaction**
  - [x] ~~Moving units (milestones [1](https://github.com/angered-ghandi/OpenAOE/milestone/1), and [3](https://github.com/angered-ghandi/OpenAOE/milestone/3))~~
  - [x] ~~Pathfind units (milestone [2](https://github.com/angered-ghandi/OpenAOE/milestone/2))~~
  - [ ] Attack units
  - [ ] Unit death
  - [ ] Drag-select units
  - [ ] Auto-attack nearby hostiles
- [ ] **GUI**
  - [ ] Font rendering
  - [ ] Top resource display
  - [ ] Bottom selected unit display
  - [ ] Bottom command buttons
- [ ] **Resources**
  - [ ] Collect wood
  - [ ] Collect food
  - [ ] Collect gold
- [ ] **Training**
  - [ ] Train units
  - [ ] Build barracks
- [ ] **Conquest victory condition**

Things that don't meet the minimum cut-off: research, hotkeys, minimap, fog of war, audio, menus, editor, AI, networked multiplayer, projectiles (ranged units).
